<?php

require 'vendor/autoload.php';

use MicrosoftAzure\Storage\Blob\BlobRestProxy;
use MicrosoftAzure\Storage\Common\Exceptions\ServiceException;
use MicrosoftAzure\Storage\Blob\Models\CreateBlockBlobOptions;

// Azure Storage account credentials
$accountName = 'mytestdemostorage';
$accountKey = 'Uq4zsEyJB+GDSsFCDUOxvozI2ANheN/wU6AIYHJQHwzWuA5Mm+Ff4E61z269Okq0t3F9ob/KQ4rr+AStLAIZbA==';
$containerName = 'demoblobstoragecontainer';

// File to upload
// $localFilePath = '/Applications/XAMPP/xamppfiles/htdocs/drupal10_poc/sites/default/files/scorm_field/valid_scorm.zip';
// //$filePath = \Drupal::service('file_system')->realpath($file->getFileUri());

// $blobName = basename($localFilePath);

// // Create Blob service client
// $connectionString = "DefaultEndpointsProtocol=https;AccountName=mytestdemostorage;AccountKey=Uq4zsEyJB+GDSsFCDUOxvozI2ANheN/wU6AIYHJQHwzWuA5Mm+Ff4E61z269Okq0t3F9ob/KQ4rr+AStLAIZbA==;EndpointSuffix=core.windows.net";

// $blobClient = BlobRestProxy::createBlobService($connectionString);

// try {
//     // Get file content
//     $content = fopen($localFilePath, "r");

//     // Set options
//     $options = new CreateBlockBlobOptions();
//     $options->setContentType(mime_content_type($localFilePath));

//     // Upload blob
//     $blobClient->createBlockBlob($containerName, $blobName, $content, $options);

//     echo "File uploaded successfully.";
// } catch (ServiceException $e) {
//     // Handle exception based on error codes and messages.
//     // Error codes and messages can be found here:
//     // https://docs.microsoft.com/rest/api/storageservices/blob-service-error-codes
//     $code = $e->getCode();
//     $error_message = $e->getMessage();
//     echo "Error code: $code\n";
//     echo "Error message: $error_message\n";
// } catch (Exception $e) {
//     echo "Error: " . $e->getMessage();
// }

// die('LOLaaa');
