<?php

/**
 * @file
 * Module functionality implementation.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_field_widget_info_alter().
 */
function scorm_field_field_widget_info_alter(array &$info) {
  $info['file_generic']['field_types'][] = 'scorm_field_scorm_package';
}

/**
 * Implements hook_theme().
 */
function scorm_field_theme() {
  return [
    'scorm_field_scorm__player' => [
      'variables' => ['decoupled_mode' => NULL, 'scorm_id' => NULL, 'node_id' => NULL, 'tree' => [], 'start_sco' => NULL],
      'template' => 'scorm-field-scorm--player',
    ],
    'scorm_field_scorm__player_tree' => [
      'variables' => ['tree' => []],
      'template' => 'scorm-field-scorm--player-tree',
    ],
    'scorm_field_scorm__player_tree_item' => [
      'variables' => ['sco' => NULL],
      'template' => 'scorm-field-scorm--player-tree-item',
    ],
    'page__scorm_field_decoupled' => [
      'base hook' => 'page',
      'template' => 'page--scorm_field_decoupled',
    ],
    'html__scorm_field_decoupled' => [
      'base hook' => 'html',
      'template' => 'html--scorm_field_decoupled',
    ],
  ];
}

/**
 * Get the available CMI paths for the SCORM player.
 *
 * Invokes the hook_scorm_field_scorm_register_cmi_paths()
 * on all implementing modules to retrieve data
 * to pass to the SCORM player.
 */
function scorm_field_scorm_add_cmi_paths($scorm_version) {
  $paths = \Drupal::moduleHandler()->invokeAll('scorm_field_scorm_register_cmi_paths', [$scorm_version]); 
  \Drupal::moduleHandler()->alter('scorm_field_scorm_register_cmi_paths', $paths);
  return $paths;
}

/**
 * Get the CMI data for the SCORM player.
 *
 * Invokes the hook_scorm_field_scorm_ui_register_cmi_data()
 * on all implementing modules to retrieve data
 * to pass to the SCORM player.
 *
 * @param object $scorm
 *   Scorm object.
 * @param array $scos
 *   Scos array.
 *
 * @return array
 *   Cmi data.
 */
function scorm_field_scorm_add_cmi_data($scorm, array $scos, $scorm_version) {
  $data = \Drupal::moduleHandler()
    ->invokeAll('scorm_field_register_cmi_data', [
      $scorm,
      $scos,
      $scorm_version,
    ]);
  \Drupal::moduleHandler()->alter('scorm_field_register_cmi_data', $data, $scorm, $scos);
  return $data;
}

/**
 * Implements hook_scorm_field_scorm_register_cmi_paths().
 */
function scorm_field_scorm_field_scorm_register_cmi_paths($scorm_version) {

  switch ($scorm_version) {
    case '2004':
      $data = [
        'cmi.location' => [],
        'cmi.completion_status' => [],
        'cmi.exit' => [],
        'cmi.entry' => [],
        'cmi.learner_id' => [],
        'cmi.learner_name' => [],
        'cmi.learner_preference._children' => [],
        'cmi.learner_preference.audio_level' => [],
        'cmi.learner_preference.language' => [],
        'cmi.learner_preference.delivery_speed' => [],
        'cmi.learner_preference.audio_captioning' => [],
        'cmi.score.raw' => [],
        'cmi.score.min' => [],
        'cmi.score.max' => [],
        'cmi.score.scaled' => [],
        'cmi.suspend_data' => [],
        'cmi.success_status' => [],
        'cmi.objectives' => [],
        'cmi.objectives._count' => ['readOnly' => 1],
        'cmi.objectives._children' => ['readOnly' => 1],
        'cmi.objectives.n.id' => [],
        'cmi.objectives.n.score' => [],
        'cmi.objectives.n.score._children' => ['readOnly' => 1],
        'cmi.objectives.n.score.scaled' => [],
        'cmi.objectives.n.score.raw' => [],
        'cmi.objectives.n.score.min' => [],
        'cmi.objectives.n.score.max' => [],
        'cmi.objectives.n.success_status' => [],
        'cmi.objectives.n.completion_status' => [],
        'cmi.objectives.n.progress_measure' => [],
        'cmi.objectives.n.description' => [],
        'cmi.interactions.n.objectives._count' => [],
        'cmi.interactions.n.objectives.n.id' => [],
        'cmi.interactions' => [],
        'cmi.interactions._count' => [],
        'cmi.interactions._children' => [],
        'cmi.interactions.n.id' => [],
        'cmi.interactions.n.type' => [],
        'cmi.interactions.n.description' => [],
        'cmi.interactions.n.result' => [],
        'cmi.interactions.n.timestamp' => [],
        'cmi.interactions.n.learner_response' => [],
        'cmi.interactions.n.correct_responses._count' => [],
        'cmi.interactions.n.correct_responses.n.pattern' => [],
      ];
      break;

    case '1.2':
      $data = [
        'cmi.core.lesson_location' => [],
        'cmi.core.lesson_status' => [],
        'cmi.core.exit' => [],
        'cmi.core.entry' => [],
        'cmi.core.student_name' => [],
        'cmi.core.student_id' => [],
        'cmi.student_preference._children' => [],
        'cmi.student_preference.audio' => [],
        'cmi.student_preference.language' => [],
        'cmi.student_preference.speed' => [],
        'cmi.student_preference.text' => [],
        'cmi.core.score._children' => [],
        'cmi.core.score.raw' => [],
        'cmi.core.score.max' => [],
        'cmi.core.score.min' => [],
        'cmi.suspend_data' => [],
        'cmi.core.lesson_status' => [],
        'cmi.objectives' => [],
        'cmi.objectives._count' => ['readOnly' => 1],
        'cmi.objectives._children' => ['readOnly' => 1],
        'cmi.objectives.n.id' => [],
        'cmi.objectives.n.score' => [],
        'cmi.objectives.n.score._children' => ['readOnly' => 1],
        'cmi.objectives.n.score.raw' => [],
        'cmi.objectives.n.score.min' => [],
        'cmi.objectives.n.score.max' => [],
        'cmi.objectives.n.status' => [],
        'cmi.interactions.n.objectives._count' => [],
        'cmi.interactions.n.objectives.n.id' => [],
        'cmi.interactions' => [],
        'cmi.interactions._count' => [],
        'cmi.interactions._children' => [],
        'cmi.interactions.n.id' => [],
        'cmi.interactions.n.type' => [],
        'cmi.interactions.n.result' => [],
        'cmi.interactions.n.timestamp' => [],
        'cmi.interactions.n.student_response' => [],
        'cmi.interactions.n.correct_responses._count' => [],
        'cmi.interactions.n.correct_responses.n.pattern' => [],
      ];
      break;
  }

  return $data;
}

/**
 * Implements hook_scorm_field_scorm_register_cmi_data().
 */
function scorm_field_scorm_field_register_cmi_data($scorm, $scos, $scorm_version) {
  $account = \Drupal::currentUser();

  if (!$account->id()) {
    $learner_name = "anonymous";
  }
  else {
    $learner_name = $account->getAccountName();
  }

  switch ($scorm_version) {
    case '2004':
      $data = [
        'cmi.location' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.location', ''),
        'cmi.completion_status' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.completion_status', 'unknown'),
        'cmi.exit' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.exit', ''),
        'cmi.entry' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.entry', ''),
        'cmi.learner_id' => $account->id(),
        'cmi.learner_name' => $learner_name,
        'cmi.learner_preference._children' => "audio_level,language,delivery_speed,audio_captioning",
        'cmi.learner_preference.audio_level' => 1,
        'cmi.learner_preference.language' => '',
        'cmi.learner_preference.delivery_speed' => 1,
        'cmi.learner_preference.audio_captioning' => 0,
        'cmi.score.raw' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.raw', ''),
        'cmi.score.min' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.min', ''),
        'cmi.score.max' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.max', ''),
        'cmi.score.scaled' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.score.scaled', ''),
        'cmi.success_status' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.success_status', ''),
        'cmi.objectives' => [],
      ];
      // Get last visited SCO.
      $last_sco = scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'user.sco', '');
      if ($last_sco != '') {
        $data['cmi.suspend_data'] = scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data.' . $last_sco, '');
      }
      else {
        $data['cmi.suspend_data'] = scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data', '');
      }
      break;

    case '1.2':
      $data = [
        'cmi.core.lesson_location' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.lesson_location', ''),
        'cmi.core.exit' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.exit', ''),
        'cmi.core.student_id' => $account->id(),
        'cmi.core.entry' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.entry', ''),
        'cmi.core.student_name' => $learner_name,
        'cmi.student_preference._children' => "audio,language,speed,text",
        'cmi.student_preference.audio' => [],
        'cmi.student_preference.language' => '',
        'cmi.student_preference.speed' => [],
        'cmi.student_preference.text' => [],
        'cmi.core.score._children' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score._children', 'raw,min,max'),
        'cmi.core.score.raw' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.raw', ''),
        'cmi.core.score.min' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.min', ''),
        'cmi.core.score.max' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.score.max', ''),
        'cmi.core.lesson_status' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.core.lesson_status', ''),
        'cmi.suspend_data' => scorm_field_default_scorm_cmi_get($account->id(), $scorm->id, 'cmi.suspend_data', ''),
        'cmi.objectives' => [],
      ];
      break;
  }

  // Fetch the objectives.
  foreach ($scos as $sco) {
    if (!empty($sco->attributes['objectives'])) {
      foreach ($sco->attributes['objectives'] as $objective) {
        $stored_objective = scorm_field_load_objective($account->id(), $scorm->id, $objective['id']);
        if ($scorm_version == '2004') {
          $defaults = [
            'id' => $objective['id'],
            'score' => [
              'scaled' => 0,
              'raw' => 0,
              'min' => 0,
              'max' => 0,
            ],
            'success_status' => '',
            'completion_status' => '',
            'progress_measure' => '',
            'description' => '',
          ];
        }
        else {
          $defaults = [
            'id' => $objective['id'],
            'score' => [
              'raw' => 0,
              'min' => 0,
              'max' => 0,
            ],
            'status' => '',
          ];
        }

        if (!empty($stored_objective)) {
          $stored_objective = (array) $stored_objective;
          $stored_objective += $defaults;
        }
        else {
          $stored_objective = $defaults;
        }

        $data['cmi.objectives'][] = $stored_objective;
      }
    }
  }

  return $data;
}

/**
 * Helper function to get SCORM CMI data while also providing a default value.
 *
 * @param int $uid
 *   User ID.
 * @param int $scorm_id
 *   Scorn ID.
 * @param string $cmi_key
 *   Cmi key.
 * @param mixed $default_value
 *   Default.
 *
 * @return mixed|null
 *   Scorm cmi.
 */
function scorm_field_default_scorm_cmi_get($uid, $scorm_id, $cmi_key, $default_value = NULL) {
  $value = scorm_field_scorm_cmi_get($uid, $scorm_id, $cmi_key);
  return isset($value) ? $value : $default_value;
}

/**
 * Get a CMI data value for the given SCORM.
 *
 * @param int $uid
 *   User ID.
 * @param int $scorm_id
 *   Scorn ID.
 * @param string $cmi_key
 *   Cmi key.
 *
 * @return mixed|null
 *   Scorm cmi.
 */
function scorm_field_scorm_cmi_get($uid, $scorm_id, $cmi_key) {
  $data = NULL;
  $result = \Drupal::database()->select('scorm_field_scorm_cmi_data', 'o')
    ->fields('o', ['value', 'serialized'])
    ->condition('o.uid', $uid)
    ->condition('o.scorm_id', $scorm_id)
    ->condition('o.cmi_key', $cmi_key)
    ->execute()
    ->fetchObject();

  if (isset($result->value)) {
    $data = !empty($result->serialized) ? unserialize($result->value) : $result->value;
  }

  return $data;
}

/**
 * Set a CMI data value for the given SCORM.
 *
 * @param int $uid
 *   User ID.
 * @param int $scorm_id
 *   Scorn ID.
 * @param string $cmi_key
 *   Cmi key.
 * @param string $value
 *   Value.
 *
 * @return bool
 *   Scorm cmi set flag.
 *
 * @throws \Exception
 */
function scorm_field_scorm_cmi_set($uid, $scorm_id, $cmi_key, $value) {
  if (isset($value)) {
    $serialized = 0;
    if (is_array($value) || is_object($value)) {
      $value = serialize($value);
      $serialized = 1;
    }
    elseif (is_bool($value)) {
      $value = (int) $value;
    }

    $result = \Drupal::database()->merge('scorm_field_scorm_cmi_data')
      ->keys([
        'uid' => $uid,
        'scorm_id' => $scorm_id,
        'cmi_key' => $cmi_key,
      ])
      ->fields([
        'uid' => $uid,
        'scorm_id' => $scorm_id,
        'cmi_key' => $cmi_key,
        'value' => $value,
        'serialized' => $serialized,
      ])
      ->execute();

    return !!$result;
  }
  else {
    return TRUE;
  }
}

/**
 * Implements hook_scorm_commit().
 */
function scorm_field_scorm_field_scorm_commit($scorm, $sco_id, $nid, $data) {
  $account = Drupal::currentUser();

  // Store objectives and results.
  if (!empty($data->cmi->objectives)) {
    for ($i = 0, $len = count($data->cmi->objectives); $i < $len; $i++) {
      scorm_field_scorm_cmi_set($account->id(), $scorm->id, "cmi.objectives.$i", $data->cmi->objectives[$i]);
    }
  }

  if (!empty($data->scorm_version)) {
    switch ($data->scorm_version) {
      case '2004':
        // Store the last visited SCO id.
        scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'user.sco', $sco_id);

        // Store the last position.
        if (!empty($data->cmi->location)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.location', $data->cmi->location);
        }

        // Store suspend data value.
        if (!empty($data->cmi->suspend_data)) {
          if (!is_null($sco_id)) {
            scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data.' . $sco_id, $data->cmi->suspend_data);
          }
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data', $data->cmi->suspend_data);
        }

        // Store the completion status.
        if (!empty($data->cmi->completion_status)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.completion_status', $data->cmi->completion_status);
        }

        // Store the score.
        if (!empty($data->cmi->score)) {
          foreach (['raw', 'min', 'max', 'scaled'] as $key) {
            if (isset($data->cmi->score->{$key})) {
              scorm_field_scorm_cmi_set($account->id(), $scorm->id, "cmi.score.{$key}", $data->cmi->score->{$key});
            }
          }
        }

        // Store the success status.
        if (!empty($data->cmi->success_status)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.success_status', $data->cmi->success_status);
        }

        break;

      case '1.2':
        // Store the last position.
        if (!empty($data->cmi->core->lesson_location)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.core.lesson_location', $data->cmi->core->lesson_location);
        }

        // Store suspend data value.
        if (!empty($data->cmi->suspend_data)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.suspend_data', $data->cmi->suspend_data);
        }

        // Store the completion status.
        if (!empty($data->cmi->core->lesson_status)) {
          scorm_field_scorm_cmi_set($account->id(), $scorm->id, 'cmi.core.lesson_status', $data->cmi->core->lesson_status);
        }

        // Store the score.
        if (!empty($data->cmi->core->score)) {
          foreach (['raw', 'min', 'max'] as $key) {
            if (isset($data->cmi->core->score->{$key})) {
              scorm_field_scorm_cmi_set($account->id(), $scorm->id, "cmi.core.score.{$key}", $data->cmi->core->score->{$key});
            }
          }
        }

        break;
    }
  }
}

/**
 * Truncates string by wanted length if necessary.
 *
 * @param string $string
 *   String to format.
 * @param int $length
 *   Necessary string length.
 *
 * @return string
 *   Formatted string.
 */
function _scorm_field_scorm_format_string_length($string, $length) {
  if (strlen($string) > $length) {
    return substr($string, 0, $length);
  }
  return $string;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function scorm_field_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type === 'node') {
    if (isset($fields['scorm_field_scorm_package'])) {
      // Use the ID as defined in the annotation of the constraint definition
      $fields['field_scorm_scorm_package']->addConstraint('ScormPackage', []);
    }
  }
}

/**
 * Implements hook_page_attachments().
 */
function scorm_field_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'scorm_field/scorm-field-scorm-ios-13';
}

/**
 * Load all objective data for the given SCORM.
 *
 * Helper function to load objective CMI data that was stored. Pass the ID
 * of the objective to fetch the data for it.
 *
 * @param int $uid
 *   User ID.
 * @param int $scorm_id
 *   Scorm ID.
 * @param string $objective_id
 *   Objective ID.
 *
 * @return object|null
 *   Objective.
 */
function scorm_field_load_objective($uid, $scorm_id, $objective_id) {
  $objectives = &drupal_static(__FUNCTION__);

  if (!isset($objectives)) {
    $result = \Drupal::database()->select('scorm_field_scorm_cmi_data', 'o')
      ->fields('o')
      ->condition('o.uid', $uid)
      ->condition('o.scorm_id', $scorm_id)
      ->condition('o.cmi_key', 'cmi.objectives.%', 'LIKE')
      ->execute();

    while ($row = $result->fetchObject()) {
      // Make sure this is one of ours.
      if (preg_match('/^cmi\.objectives\.[0-9]+$/', $row->cmi_key)) {
        $data = unserialize($row->value);

        // Allow modules to alter the data.
        $context = [
          'uid' => $uid,
          'scorm_id' => $scorm_id,
          'original_value' => $data,
        ];

        $objectives[$data->id] = $data;
      }
    }
  }

  return isset($objectives[$objective_id]) ? $objectives[$objective_id] : NULL;
}


function scorm_field_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  
  $route_name = \Drupal::routeMatch()->getRouteName();

  if (isset($route_name) && $route_name === 'scorm_field.decoupled')  {
    $suggestions[] = 'page__scorm_field_decoupled';
  }

}

function scorm_field_theme_suggestions_html_alter(array &$suggestions, array $variables) {
  
  $route_name = \Drupal::routeMatch()->getRouteName();

  if (isset($route_name) && $route_name === 'scorm_field.decoupled')  {
    $suggestions[] = 'html__scorm_field_decoupled';
  }

}






